#!/usr/bin/bash

function main() {
  local wpa_conf
  local int
  local exec_path
  local pid4
  local pid6
  local count=10

  while getopts 'c:hi:' opt; do
    case "${opt}" in
      c) wpa_conf="${OPTARG}" ;;
      i) int="${OPTARG}" ;;
      h) help 0 ;;
      *) help 1 ;;
    esac
  done

  [[ "$UID" == 0 ]] || { echo "Must be root" >&2; exit 2; }
  [[ -n "${int}" && -n "${wpa_conf}" ]] || help 3

  exec_path="$(dirname "$0")"

  "${exec_path}"/pssid-80211 -c "${wpa_conf}" -i "${int}" > 80211-start.json
  "${exec_path}"/pssid-dhcp -i "${int}" > dhcp-start.json

  ping \
    -c "${count}" \
    -i 0.2 \
    -I "$(ip -j addr show wlan0 | jq -r '.[].addr_info[] | select(.family == "inet").local')" \
    1.1.1.1 &
  pid4=$!
  ping \
    -c "${count}" \
    -i 0.2 \
    -I "$(ip -j addr show wlan0 | jq -r '.[].addr_info[] | select(.family == "inet6" and .scope == "global" and .temporary != "true").local')" \
    2606:4700:4700::1111 &
  pid6=$!

  wait $pid4 $pid6

  "${exec_path}"/pssid-dhcp -i "${int}" -d > dhcp-end.json
  "${exec_path}"/pssid-80211 -c "${wpa_conf}" -i "${int}" -d > 80211-end.json
}

function help() {
  local -i exit_code="$1"
  local self
  self="$(basename "$0")"
  echo "Usage: ${self} -c <wpa_supplicant.conf> -i <wlan interface>"
  exit "${exit_code}"
}

main "$@"
