#!/usr/bin/bash

#
# pssid-dhcp
# A command run by pssid to gather dhcp metrics
#
# External programes used:
# - base64
# - bc
# - cut
# - grep
# - jq
# - tail
# - dhcpcd
# - zstd

source "$(dirname "$0")/libpssid.sh"
declare JSON
JSON="$(jq \
		--null-input \
		--compact-output \
		--argjson base "$(base_json)" \
		--argjson none "$(none)" \
		'$base
		| .internal += {
			"pcap": {
				"file": "/tmp/pssid-dhcp.pcap",
				"enabled": false
			}
		}'
	)" \
	|| exit 255
declare -r DHCPCD_LOG_FILE='/tmp/pssid-dhcpcd.log'

function main() {
	local -i disconnect=0
	local -i dhcpcd_exit_status

	while getopts 'di:hv' opt; do
		case "${opt}" in
			d) disconnect=1 ;;
			i) set_interface "${OPTARG}" ;;
			v) increase_verbosity ;;
			h) help 0 ;;
			*) help 64 ;;
		esac
	done

	[[ "$UID" == 0 ]] || be_done 65 'Must be root'
	get_interface > /dev/null || be_done 66 'Must specify the interface'
	[[ "${disconnect}" == 1 ]] && release
	dhcpcd_running \
		&& release 67 "dhcpcd already running; releasing and cleaning up"

	if [[ -f "${DHCPCD_LOG_FILE}" ]]; then
		log 1 "WARNING: log file '${DHCPCD_LOG_FILE}' already exists -- removing"
		rm "${DHCPCD_LOG_FILE}" || be_done 254 "Error removing old log file"
	fi

	get_addrs
	log 0 "dhcpcd started"
	dhcpcd "$(get_interface || panic)" -j "${DHCPCD_LOG_FILE}"
	dhcpcd_exit_status=$?
	log 0 "dhcpcd exited with status ${dhcpcd_exit_status}"
	get_addrs
	# TODO: get pcap and protocol duration

	[[ 0 -eq ${dhcpcd_exit_status} ]] \
		|| set_status 1 "dhcpcd exited with error status ${dhcpcd_exit_status}"
	be_done
}

function get_addrs() {
	log 1 "Getting $(get_interface || panic) addresses)"
	JSON="$(jq \
		--compact-output \
		--argjson info "$(ip -j addr show "$(get_interface || panic)")" \
		'.addr_info += [$info]' \
		<<< "${JSON}"
	)"
}

function help() {
	local self
	self="$(basename "$0")"
	echo "Connect with: $self -i <wlan interface> [-v]"
	echo "Disconnect with: $self -d -i <wlan interface> [-v]"
	exit "$1"
}

function release() {
	[[ $# -ge 2 ]] && set_status "$@"

	get_addrs
	log 0 "Releasing addresses"
	dhcpcd -k "$(get_interface || panic)" \
		|| set_status 2 "dhcpcd exited with status $? on release"
	log 1 "Addresses released"
	get_addrs
	if [[ -f "${DHCPCD_LOG_FILE}" ]]; then
		JSON="$(jq \
			--compact-output \
			--arg log "$(encode < "${DHCPCD_LOG_FILE}")" \
			'.dhcpcd_log = $log' \
			<<< "${JSON}"
		)"
		rm "${DHCPCD_LOG_FILE}" \
			|| log 1 "WARNING: unable to cleanup log file '${DHCPCD_LOG_FILE}'"
	fi
	be_done
}

function dhcpcd_running() {
	[[ -f "/run/dhcpcd/$(get_interface || panic).pid" ]]
}

main "$@"

# vim: ts=4 sts=4 sw=4 noexpandtab
